name: Build release

on:
  push:
    tags:
      - 'r*'
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Build application
      run: bun run build
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "test tag name"
        files: ./dist
  
